/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package travelmania;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author dhananji
 */
public class create_a_trip extends javax.swing.JFrame {

    /**
     * Creates new form places
     */
    public create_a_trip() {
        initComponents();
    }
    
    private boolean cheackEmptyFields(){
        
        if(txtUserName.getText().isEmpty() | txtStartPoint.getText().isEmpty() | txtEndPoint.getText().isEmpty() | 
                txtDatesAmo.getText().isEmpty() | txtMembers.getText().isEmpty()){
        
            JOptionPane.showMessageDialog(this, "Please fill all details");
            
            return false;
        }
    
        return true;
    
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        tripStartDate = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtStartPoint = new javax.swing.JTextField();
        txtEndPoint = new javax.swing.JTextField();
        txtMembers = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtDatesAmo = new javax.swing.JTextField();
        txtEndDate = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        txtTripId = new javax.swing.JTextField();
        txtTripName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(0, 255, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Create Trip");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, -1, -1));

        tripStartDate.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(tripStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 400, -1));

        jLabel4.setBackground(new java.awt.Color(0, 255, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Create Your Trip");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 220, 40));

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Trip Name");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 160, 20));

        jLabel3.setBackground(new java.awt.Color(204, 255, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Start point");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 160, 20));

        jLabel5.setBackground(new java.awt.Color(204, 255, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("End point");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 160, 20));

        jLabel6.setBackground(new java.awt.Color(204, 255, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Start Date");
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 160, 20));

        jLabel7.setBackground(new java.awt.Color(204, 255, 204));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Dates amount");
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 160, 20));

        jLabel8.setBackground(new java.awt.Color(204, 255, 204));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Trip ID");
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 160, 20));
        jPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 400, -1));

        txtStartPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartPointActionPerformed(evt);
            }
        });
        jPanel1.add(txtStartPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 400, -1));

        txtEndPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndPointActionPerformed(evt);
            }
        });
        jPanel1.add(txtEndPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 400, -1));

        txtMembers.setColumns(20);
        txtMembers.setRows(5);
        jPanel1.add(txtMembers, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 400, 100));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("End Date");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 160, 20));

        txtDatesAmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatesAmoActionPerformed(evt);
            }
        });
        jPanel1.add(txtDatesAmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 400, 20));

        txtEndDate.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(txtEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 400, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 90, -1));

        txtTripId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTripIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtTripId, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 400, -1));

        txtTripName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTripNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtTripName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 400, -1));

        jLabel9.setBackground(new java.awt.Color(204, 255, 204));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Username");
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 160, 20));

        jLabel10.setBackground(new java.awt.Color(204, 255, 204));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Members");
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 160, 20));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/World.jpg"))); // NOI18N
        background.setOpaque(true);
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String TripName = txtTripName.getText();
        String UserName = txtUserName.getText();
        String TripId = txtTripId.getText();
        String StartPoint = txtStartPoint.getText();
        //String ConPass=String.valueOf(txtConPass.getPassword());
        String EndPoint = txtEndPoint.getText();
        //Date eStartDate = tripStartDate.getDate();
        //Date eEndDate = txtEndDate.getDate();
        
        //String StartDate = eStartDate.toString();
        //String EndDate = eEndDate.toString();
        //String strStartDate = dateFormat.format(date);

        String NoDays = txtDatesAmo.getText();
        String Members = txtMembers.getText();
        
        PreparedStatement ps;
        ResultSet rs;
        
        
        String query = "INSERT INTO `create a trip` (`Username`,`Trip Name`,`Trip Id`,`From`,`To`,`Number of Days`,`startp`,`endp`,`Discription`) VALUES (?,?,?,?,?,?,?,?,?)";
        
        try {
            ps = Database_Connector.getConnection().prepareStatement(query);
            ps.setString(1, UserName);
            ps.setString(2, TripName);
            ps.setString(3, TripId);
            ps.setString(4, ((JTextField) tripStartDate.getDateEditor().getUiComponent()).getText());
            ps.setString(5, ((JTextField) txtEndDate.getDateEditor().getUiComponent()).getText());
            ps.setString(6, NoDays);
            ps.setString(7, StartPoint);
            ps.setString(8, EndPoint);
            ps.setString(9, Members);
            
            ps.execute();
            
            JOptionPane.showMessageDialog(null, "Trip Created Successfully");
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
            Logger.getLogger(create_a_trip.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        travelmaniadashboard dash;
        dash = new travelmaniadashboard();
                
        dash.setVisible(true);
        dash.pack();
        dash.setLocationRelativeTo(null);
        dash.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtEndPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndPointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndPointActionPerformed

    private void txtStartPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartPointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartPointActionPerformed

    private void txtDatesAmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatesAmoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatesAmoActionPerformed

    private void txtTripNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTripNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTripNameActionPerformed

    private void txtTripIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTripIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTripIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(create_a_trip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(create_a_trip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(create_a_trip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(create_a_trip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new create_a_trip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser tripStartDate;
    private javax.swing.JTextField txtDatesAmo;
    private com.toedter.calendar.JDateChooser txtEndDate;
    private javax.swing.JTextField txtEndPoint;
    private javax.swing.JTextArea txtMembers;
    private javax.swing.JTextField txtStartPoint;
    private javax.swing.JTextField txtTripId;
    private javax.swing.JTextField txtTripName;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
