/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TravelMania;

/**
 *
 * @author User
 */
public class destinationspage extends javax.swing.JFrame {

    /**
     * Creates new form destinationspage
     */
    public destinationspage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        D1 = new javax.swing.JButton();
        D2 = new javax.swing.JButton();
        D3 = new javax.swing.JButton();
        D4 = new javax.swing.JButton();
        D5 = new javax.swing.JButton();
        D6 = new javax.swing.JButton();
        D7 = new javax.swing.JButton();
        D8 = new javax.swing.JButton();
        D9 = new javax.swing.JButton();
        D10 = new javax.swing.JButton();
        D21 = new javax.swing.JButton();
        D22 = new javax.swing.JButton();
        D23 = new javax.swing.JButton();
        D24 = new javax.swing.JButton();
        D25 = new javax.swing.JButton();
        D26 = new javax.swing.JButton();
        D27 = new javax.swing.JButton();
        D28 = new javax.swing.JButton();
        D29 = new javax.swing.JButton();
        D30 = new javax.swing.JButton();
        back1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Travel Destinations");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 390, 50));

        back.setBackground(new java.awt.Color(0, 204, 204));
        back.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Covid - 19 Updates");
        back.setOpaque(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 550, 190, 30));

        D1.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        D1.setText("Adam's Peak, Rathnapura");
        D1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D1ActionPerformed(evt);
            }
        });
        jPanel1.add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 300, 20));

        D2.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        D2.setText("Temple of Tooth Relic, Kandy");
        D2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D2ActionPerformed(evt);
            }
        });
        jPanel1.add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 300, 20));

        D3.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        D3.setText("Ella, Badulla");
        D3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D3ActionPerformed(evt);
            }
        });
        jPanel1.add(D3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 300, 20));

        D4.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        D4.setText("Galle Fort, Galle");
        D4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D4ActionPerformed(evt);
            }
        });
        jPanel1.add(D4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 300, 20));

        D5.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        D5.setText("Mandaram Nuwara, Nuwara-Eliya");
        D5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D5ActionPerformed(evt);
            }
        });
        jPanel1.add(D5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 300, 20));

        D6.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        D6.setText("Mirissa, Galle");
        D6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D6ActionPerformed(evt);
            }
        });
        jPanel1.add(D6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 300, 20));

        D7.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        D7.setText("Nilaweli, Trincomalee");
        D7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D7ActionPerformed(evt);
            }
        });
        jPanel1.add(D7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 300, 20));

        D8.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        D8.setText("Sacred City, Anuradhapura");
        D8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D8ActionPerformed(evt);
            }
        });
        jPanel1.add(D8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 300, 20));

        D9.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        D9.setText("Nine Arch, Badulla");
        D9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D9ActionPerformed(evt);
            }
        });
        jPanel1.add(D9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 300, 20));

        D10.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        D10.setText("Pinnawala Elephant Orphanage, Kegalle");
        D10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D10ActionPerformed(evt);
            }
        });
        jPanel1.add(D10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 300, 20));

        D21.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        D21.setText("Kabaragala, Rathnapura");
        D21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D21ActionPerformed(evt);
            }
        });
        jPanel1.add(D21, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 300, 20));

        D22.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        D22.setText("Yapahuwa Kingdom, Kurunegala");
        D22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D22ActionPerformed(evt);
            }
        });
        jPanel1.add(D22, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 300, 20));

        D23.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        D23.setText("Ambuluwawa, Gampola");
        D23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D23ActionPerformed(evt);
            }
        });
        jPanel1.add(D23, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 300, 20));

        D24.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        D24.setText("Meeyan-Ella, Kegalle");
        D24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D24ActionPerformed(evt);
            }
        });
        jPanel1.add(D24, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 300, 20));

        D25.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        D25.setText("Pidurangala, Matale");
        D25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D25ActionPerformed(evt);
            }
        });
        jPanel1.add(D25, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 300, 20));

        D26.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        D26.setText("Yala National Park, Hambanthota");
        D26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D26ActionPerformed(evt);
            }
        });
        jPanel1.add(D26, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 300, 20));

        D27.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        D27.setText("Hikkaduwa, Galle");
        D27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D27ActionPerformed(evt);
            }
        });
        jPanel1.add(D27, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 300, 20));

        D28.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        D28.setText("Kithulgala, Kegalle");
        D28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D28ActionPerformed(evt);
            }
        });
        jPanel1.add(D28, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 300, 20));

        D29.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        D29.setText("Sinharaja, Galle");
        D29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D29ActionPerformed(evt);
            }
        });
        jPanel1.add(D29, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 300, 20));

        D30.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        D30.setText("Horton Planes, Nuwara-Eliya");
        D30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D30ActionPerformed(evt);
            }
        });
        jPanel1.add(D30, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 300, 20));

        back1.setBackground(new java.awt.Color(0, 51, 51));
        back1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        back1.setForeground(new java.awt.Color(255, 255, 255));
        back1.setText("Back");
        back1.setOpaque(false);
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });
        jPanel1.add(back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 80, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Destination.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        
    }//GEN-LAST:event_backActionPerformed

    private void D1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D1ActionPerformed
        Place_adamspeak m = new Place_adamspeak();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D1ActionPerformed

    private void D2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D2ActionPerformed
        Place_DaladaMaligawa m = new Place_DaladaMaligawa();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D2ActionPerformed

    private void D3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D3ActionPerformed
        Place_Ella m = new Place_Ella();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D3ActionPerformed

    private void D4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D4ActionPerformed
        Place_GalleFort m = new Place_GalleFort();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D4ActionPerformed

    private void D5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D5ActionPerformed
        Place_Mandaramnuwara m = new Place_Mandaramnuwara();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D5ActionPerformed

    private void D6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D6ActionPerformed
        Place_Mirissa m = new Place_Mirissa();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D6ActionPerformed

    private void D7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D7ActionPerformed
        Place_Nilaweli m = new Place_Nilaweli();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D7ActionPerformed

    private void D8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D8ActionPerformed
        Place_Anuradapura m = new Place_Anuradapura();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D8ActionPerformed

    private void D9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D9ActionPerformed
        Place_ninearch m = new Place_ninearch();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D9ActionPerformed

    private void D10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D10ActionPerformed
        Place_PinnwalaEO m = new Place_PinnwalaEO();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D10ActionPerformed

    private void D21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D21ActionPerformed
        Place_Kabaragala m = new Place_Kabaragala();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D21ActionPerformed

    private void D22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D22ActionPerformed
        Place_Yapahuwa m = new Place_Yapahuwa();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D22ActionPerformed

    private void D23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D23ActionPerformed
        Place_Ambuluwawa m = new Place_Ambuluwawa();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D23ActionPerformed

    private void D24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D24ActionPerformed
        Place_Meeyanella m = new Place_Meeyanella();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D24ActionPerformed

    private void D25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D25ActionPerformed
        Place_Pidurangala m = new Place_Pidurangala();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D25ActionPerformed

    private void D26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D26ActionPerformed
        Place_yala m = new Place_yala();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D26ActionPerformed

    private void D27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D27ActionPerformed
        place_hikkaduwa m = new place_hikkaduwa();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D27ActionPerformed

    private void D28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D28ActionPerformed
        Place_kithulgala m = new Place_kithulgala();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D28ActionPerformed

    private void D29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D29ActionPerformed
        Place_sinharaja m = new Place_sinharaja();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D29ActionPerformed

    private void D30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D30ActionPerformed
        place_hortonplane m = new place_hortonplane();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D30ActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        
    }//GEN-LAST:event_back1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(destinationspage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(destinationspage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(destinationspage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(destinationspage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new destinationspage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton D1;
    private javax.swing.JButton D10;
    private javax.swing.JButton D2;
    private javax.swing.JButton D21;
    private javax.swing.JButton D22;
    private javax.swing.JButton D23;
    private javax.swing.JButton D24;
    private javax.swing.JButton D25;
    private javax.swing.JButton D26;
    private javax.swing.JButton D27;
    private javax.swing.JButton D28;
    private javax.swing.JButton D29;
    private javax.swing.JButton D3;
    private javax.swing.JButton D30;
    private javax.swing.JButton D4;
    private javax.swing.JButton D5;
    private javax.swing.JButton D6;
    private javax.swing.JButton D7;
    private javax.swing.JButton D8;
    private javax.swing.JButton D9;
    private javax.swing.JButton back;
    private javax.swing.JButton back1;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
